version: "3.9"

services:
  node:
    image: ghcr.io/zerocluster/node

    build:
      context: .
      args:
        UBUNTU_VERSION: "22.04"
        NODE_VERSION: lts
        # NPM_VERSION: latest

  app:
    depends_on: [node]
    image: ghcr.io/zerocluster/node/app

    build:
      context: .
      dockerfile: Dockerfile-app
