version: "3.9"

services:
  node:
    image: ghcr.io/zerocluster/node

    build:
      context: .

  app:
    depends_on: [node]
    image: ghcr.io/zerocluster/node/app

    build:
      context: .
      dockerfile: app.dockerfile

x-build:
  default_tag: latest
  # auto_tags: [main, latest, next]
